books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": 1234,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Django By Example",
        "author": "Antonio Mele",
        "publisher": "Packt Publishing Ltd",
        "published_date": "2022-01-19",
        "page_count": 1023,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2020-07-15",
        "page_count": 792,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "publisher": "Pearson",
        "published_date": "2019-05-10",
        "page_count": 480,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Python Crash Course",
               "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2021-11-02",
        "page_count": 544,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "published_date": "2020-02-18",
        "page_count": 592,
        "language": "English",
    },
]